#!/bin/bash -e

APP_NAME="prism-lts"
CONTAINER_NAME="$APP_NAME"
PORT_NUM=

function help_message {
  echo '
Valid Options are:

-h         This help prompt

'
}

echo "Tailing logs for $APP_NAME"


function tail_logs {
  kubectl logs -f $(kubectl get po -o name -l app=$APP_NAME --sort-by='.metadata.creationTimestamp' | cut -d \/ -f 2 | tail -n 1) -c $CONTAINER_NAME
}

tail_logs