kafkaConnect:
  replicaCount: 1
  imageSecretName: "quay-sts"
  image: "quay.io/stsatlas/schwartz-kafka-connect:9ea5066a9f2f50220a3982dd03ba23ffde86ba63"
  connectInternalKeyConverter: "org.apache.kafka.connect.json.JsonConverter"
  connectInternalValueConverter: "org.apache.kafka.connect.json.JsonConverter"
  connectKeyConverter: "io.confluent.connect.avro.AvroConverter"
  connectValueConverter: "io.confluent.connect.avro.AvroConverter"

k8sJob:
  imageSecretName: "quay-sts"
  image: "quay.io/stsatlas/bash-curl:21d470eaddc292462c07d08ca19319caf2e55417"

healthMetricsConnectJob:
  name: "lts-test-health-metrics-kc-job"
  topics: "health-metrics"
  timestampExtractor: "Record"
  flushSize: 1
  s3BucketName: "prism-lts-local"

acUserEventConnectJob:
  name: "lts-test-ac-user-event-kc-job"
  topics: "ac-user-event"
  timestampExtractor: "Record"
  flushSize: 1
  s3BucketName: "prism-lts-local"

tags:
  prism-lts-local-values: false
  prism-lts-dev-values: false
  prism-lts-test-values: false
  prism-lts-prod-values: false
