kafkaConnect:
  kafkaServers: "local-kafka:9092"
  heapOpts: "-Xms64m -Xmx128m"
  restartPolicy: "Always"
  replicaCount: 1
  s3SecretName: "aws-s3-creds"
  imageSecretName: "quay-sts"
  image: "quay.io/stsatlas/prism-lts"
  tag: "latest"
  connectKeyConverterSchemaRegistryUrl: "http://local-schema-registry:8081"
  connectValueConverterSchemaRegistryUrl: "http://local-schema-registry:8081"
  connectInternalKeyConverter: "org.apache.kafka.connect.json.JsonConverter"
  connectInternalValueConverter: "org.apache.kafka.connect.json.JsonConverter"
  connectKeyConverter: "io.confluent.connect.avro.AvroConverter"
  connectValueConverter: "io.confluent.connect.avro.AvroConverter"
  storageReplicationFactor: 1

jmxExporter:
  resources: false

s3ConnectorJob:
  name: "s3-connector-job"
  imageSecretName: "quay-sts"
  image: "quay.io/stsatlas/bash-curl"
  tag: "latest"
  resources: false
  topics:
  - "health-metrics"
  - "ac-user-event"
  - "saas-usage-metrics"
  - "site-modules"
  - "site-usage-metrics"
  - "sites"
  - "site-usage-interval-metrics"
  - "load-test-saas"
  - "site-user-consent"
  config:
    CONNECTOR_NAME: "s3-connector"
    FLUSH_SIZE: 2
    ROTATE_INTERVAL: 5000
    S3_BUCKET_NAME: "local-prism-lts"
    PRISM_LTS_HOST: "prism-lts"

tags:
  prism-lts-local-values: false
  prism-lts-test-values: false
  prism-lts-prod-values: false
