version: 2
jobs:
  test:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - run:
          name: save unique bucket name to file
          command: echo "s3://connect-test-$(uuidgen)" > .s3-bucket-name
      - run:
          command: |
            ./bin/install-minikube-and-helm
            ./bin/run-helm-chart
      - run:
          command: |
            sudo kubectl get all
      - run:
          name: clean up s3 bucket
          command: cat .s3-bucket-name | aws s3 rm --recursive && cat .s3-bucket-name | aws s3 rb
          when: always
      - save_cache:
          path: ~/repo
          key: repo-{{ checksum ".circle-sha" }}
  deploy_dev:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bin/kube-deploy dev
            fi

  deploy_prod:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bin/kube-deploy prod
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy_dev:
          requires:
            - test
      - deploy_prod:
          requires:
            - test
