version: 2
jobs:
  test:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - run:
          command: |
            ./bin/install-minikube-and-helm
            ./bin/run-helm-chart
      - save_cache:
          paths:
            - ~/repo
            - ~/.helm
            - /usr/local/bin/helm
          key: repo-{{ checksum ".circle-sha" }}
  deploy_dev:
    machine: true
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Running the dev deploy right meow!!!"
              ./bin/kube-deploy dev
            fi

  deploy_prod:
    machine: true
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Running the prod deploy right meow!!!"
              ./bin/kube-deploy prod
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy_dev:
          requires:
            - test
      - deploy_prod:
          requires:
            - test
