version: 2
jobs:

  build_image:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: bin/build-image
  test:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - run:
          command: |
            sudo chown -R $USER /usr/local/bin && sudo chgrp -R $USER /usr/local/bin
            ./bin/install-minikube-and-helm
            ./bin/run-kafka-connect-test
            cp -r /usr/local/bin/helm $HOME/helm
      - save_cache:
          paths:
            - ~/repo
            - ~/.helm
            - ~/helm
          key: repo-{{ checksum ".circle-sha" }}

  deploy_prod:
    machine: true
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Running the prod deploy right meow!!!"
              sudo chown -R $USER /usr/local/bin && sudo chgrp -R $USER /usr/local/bin
              cp -r $HOME/helm /usr/local/bin/helm
              ./bin/kube-deploy prod
            fi

workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 17 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
      - deploy_prod:
          requires:
            - test
  commit:
    jobs:
      - build_image
      - test:
          requires:
            - build_image
      - deploy_prod:
          requires:
            - test
