apiVersion: v1
data:
  config.yml: |
    ---
    startDelaySeconds: 5
    hostPort: 127.0.0.1:1234
    ssl: false
    rules:
      - pattern: ".*"
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-jmx-config
