apiVersion: v1
kind: ConfigMap
metadata:
  name: health-metrics-job-script
data:
  health-metrics-kafka-connect-s3-job: |
    #!/bin/bash
    domain_name={{ .Values.healthMetricsConnectJob.serviceDomainName | quote }}
    connect_job_name={{ .Values.healthMetricsConnectJob.name | quote }}
    connector_url="http://$domain_name:8083/connectors/$connect_job_name/config"

    curl -i --connect-timeout 10 --fail -X PUT \
       -H "Accept:application/json" \
       -H "Content-Type:application/json" \
       -d \
    '{
    "name":"{{ .Values.healthMetricsConnectJob.name }}",
    "connector.class":"io.confluent.connect.s3.S3SinkConnector",
    "schema.generator.class":"io.confluent.connect.storage.hive.schema.TimeBasedSchemaGenerator",
    "format.class":"io.confluent.connect.s3.format.avro.AvroFormat",
    "storage.class":"io.confluent.connect.s3.storage.S3Storage",
    "partitioner.class":"schwartz_kafka_connect.partitioner.DailyPartitioner",
    "schema.compatibility":"NONE",
    "tasks.max":"12",
    "s3.part.size":"5242880",
    "topics":"{{ .Values.healthMetricsConnectJob.topics }}",
    "path.format":"'"'"'year'"'"'=YYYY/'"'"'month'"'"'=MM/'"'"'day'"'"'=dd",
    "locale":"us",
    "rotate.interval.ms":"120000",
    "timestamp.extractor":"schwartz_kafka_connect.SchwartzTimestampExtractor",
    "timestamp.field":"metric_date",
    "timezone":"UTC",
    "flush.size":"{{ .Values.healthMetricsConnectJob.flushSize }}",
    "s3.bucket.name":"{{ .Values.healthMetricsConnectJob.s3BucketName }}"
    }' \
    "$connector_url"
