apiVersion: v1
kind: ConfigMap
metadata:
  name: health-metrics-job-script
data:
  health-metrics-kafka-connect-s3-job: |
    #!/bin/bash
    connector_url="http://"{{ .Values.healthMetricsConnectJob.serviceDomainName | quote }}":8083/connectors"
    { curl -i "$connector_url/"{{ .Values.healthMetricsConnectJob.name | quote }} | grep '200 OK'; } && exit 0

    curl -i --connect-timeout 10 --fail -X POST \
       -H "Accept:application/json" \
       -H "Content-Type:application/json" \
       -d \
    '{"name":"{{ .Values.healthMetricsConnectJob.name }}",
     "config":
    {
    "name":"{{ .Values.healthMetricsConnectJob.name }}",
    "connector.class":"io.confluent.connect.s3.S3SinkConnector",
    "schema.generator.class":"io.confluent.connect.storage.hive.schema.TimeBasedSchemaGenerator",
    "format.class":"io.confluent.connect.s3.format.avro.AvroFormat",
    "storage.class":"io.confluent.connect.s3.storage.S3Storage",
    "partitioner.class":"io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
    "partition.duration.ms":"3000000",
    "schema.compatibility":"BACKWARD",
    "tasks.max":"12",
    "topics":"{{ .Values.healthMetricsConnectJob.topics }}",
    "path.format":"'"'"'year'"'"'=YYYY/'"'"'month'"'"'=MM/'"'"'day'"'"'=dd",
    "locale":"en",
    "timestamp.extractor":"RecordField",
    "timestamp.field":"metric_date",
    "timezone":"UTC",
    "flush.size":"{{ .Values.healthMetricsConnectJob.flushSize }}",
    "s3.bucket.name":"{{ .Values.healthMetricsConnectJob.s3BucketName }}"
    }}' \
    "$connector_url"
