apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.kafka.name }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.kafka.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.kafka.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.kafka.repository }}:{{ .Values.kafka.imageTag }}"
        imagePullPolicy: Always
        name: kafka
        resources: {}
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "{{ .Values.zookeeper.name }}:2181"
        ports:
        - containerPort: 9092
          protocol: TCP
        command:
        - sh
        - -c
        - |
          export KAFKA_BROKER_ID=1 && \
          export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://${POD_IP}:9092" && \
          /etc/confluent/docker/run
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
