apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.restProxy.name }}
  labels:
    app: {{ .Values.restProxy.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8082
      protocol: TCP
      name: rest-proxy
  selector:
    app: {{ .Values.restProxy.name }}
    release: {{ .Release.Name }}
