apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.schemaRegistry.name  }}
  labels:
    app: {{ .Values.schemaRegistry.name  }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      name: schema-registry
  selector:
    app: {{ .Values.schemaRegistry.name  }}
    release: {{ .Release.Name }}
