#!/bin/bash
connector_url="http://$PRISM_LTS_HOST:8083/connectors/$CONNECTOR_NAME/config"
data=$(envsubst < /tmp/payload.json)

curl -X PUT -i --connect-timeout 10 --fail \
   --url "$connector_url" \
   -H "Accept:application/json" \
   -H "Content-Type:application/json" \
   -d "$data"
