version: 2
jobs:
  checkout_code:
    docker:
      - image: confluentinc/cp-kafka-connect:3.2.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/repo

  test:
    docker:
      - image: confluentinc/cp-kafka-connect:3.2.2
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - run:
          name: Test
          command: echo 'This test is absolutely foolproof.'

  deploy_dev:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bin/kube-deploy dev
            fi

  deploy_prod:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bin/kube-deploy prod
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - test_entitled:
          requires:
            - checkout_code
      - build_image:
          requires:
            - test
      - deploy_dev:
          requires:
            - build_image
      - deploy_prod:
          requires:
            - build_image
